name: Compile Sketch

on:
  push:
    branches: [dev, release/stm32-blackpill]
  pull_request:
    branches: [dev, release/stm32-blackpill]
  # Manual trigger
  workflow_dispatch:

jobs:
  coding-style:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install eclint
        run: |
          npm install -g eclint

      - name: Check coding style
        run: |
          eclint check $(sh .eclint-files.sh)

  compile-sketch:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install Platformio
        run: |
          python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

      - name: Build the main project
        run: |
          ~/.platformio/penv/bin/platformio run -e blackpill-dfu

      - name: Build scales
        run: |
          ~/.platformio/penv/bin/platformio run -e scales-calibration-dfu

      - name: Run tests
        run: |
          ~/.platformio/penv/bin/platformio test -e test
